name: Create GitHub Repository

on:
  workflow_dispatch:
    inputs:
      repo_name:
        required: true
        description: Name of the new repository
        type: string
      port_context:
        required: true
        description: Port run context
        type: string

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Repository
        uses: port-labs/cookiecutter-gha@v1.1.1
        with:
          portClientId: ${{ secrets.PORT_CLIENT_ID }}
          portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_context).runId }}
          repositoryName: ${{ inputs.repo_name }}
          portUserInputs: '{"cookiecutter_app_name": "${{ inputs.repo_name }}"}'
          cookiecutterTemplate: https://github.com/lacion/cookiecutter-golang
          blueprintIdentifier: "githubRepository"
          organizationName: nimeshjain1
          createPortEntity: true

      - name: Report failure to Port
        if: failure()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.port.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          status: "FAILURE"
          summary: "Failed to create repository"

